apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      component: grafana
  template:
    metadata:
      labels:
        component: grafana
    spec:
      containers:
      # Data source backend serving metrics accessed by Grafana:
      - name: datasource
        image: f0bec0d/datasource-clj
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

      # Grafana backend:
      - name: grafana
        image: grafana/grafana:6.4.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: "/var/lib/grafana"
          name: "var-lib-grafana"

      # The Volume must be writable by Grafana user. Without this init
      # container you would have to manually do this:
      #
      #   mkdir -p /var/lib/k3s-volumes/var-lib-grafana/
      #   chown 472:472 /var/lib/k3s-volumes/var-lib-grafana/
      #   chmod 700 /var/lib/k3s-volumes/var-lib-grafana/
      #
      # FIXME: what if the UID or GID change?
      initContainers:
      - name: "chown-n-chmod"
        image: "busybox:1.31"
        command: ["sh", "-c", "chown 472:472 /d && chmod 700 /d"]
        volumeMounts:
        - mountPath: "/d"
          name: "var-lib-grafana"
      volumes:
      - name: "var-lib-grafana"
        hostPath:
          path: "/var/lib/k3s-volumes/var-lib-grafana"
          type: "DirectoryOrCreate"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: ClusterIP
  selector:
    component: grafana
  ports:
  - port: 3000
    targetPort: 3000
---
#
# We assume here that *.localhost resolves to the local machine.  Following
# URLs should be directed to Grafana.
#
#     http://grafana.localhost
#     https://grafana.localhost
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  rules:
  - host: grafana.localhost
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
