# kubectl apply -k .
namespace: datasource-clj
namePrefix: "datasource-"
nameSuffix: ""
commonLabels:
  app: "datasource"
commonAnnotations:
  change-this-to-reapply: "1"
configMapGenerator:
  - name: "datasources"
    files:
      - "datasources.yaml"
  - name: "dashboard-providers"
    files:
      - "dashboard-providers.yaml"
  - name: "dashboards"
    files:
      - "simple-dashboard.json"
resources:
  - datasource.yaml
